### PR TITLE
fix typing for createI18nMessage (fix #972)

### LINKED ISSUE #972: Property '$valid' is missing with Typescript
I'm trying to implement  i18n with Vuelidate as the example in https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support in a Typescript project

But I got the following error with the minLength validator as well as minValue or sameAs (with the required validator  it's working fine):
```js
export const minLength = withI18nMessage(validators.minLength, { withArguments: true })
```
```
Property '$valid' is missing in type 'ValidationRuleWithParams<{ length: number; }, any>' but required in type 'ValidatorResponse'.
```

Packages version:
@vuelidate/core: "^2.0.0-alpha.32",
@vuelidate/validators: "^2.0.0-alpha.25",
vue-i18n: "^9.2.0-beta.17",

### PR DESCRIPTION
**Pull request by derdem**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe: typing

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v1.x (or to a previous version branch), _not_ the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing: https://github.com/vuelidate/vuelidate/blob/master/.github/CONTRIBUTING.md#development-setup
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

I didn't know how to test the changes other than to create a file, composing all validators with the createI18nMessage function and checking that no typescript error is thrown. The function `notValidator` was added as a reference and should throw an error of course. 

Screenshot 2021-12-07 at 09 13 09

### CODE REVIEW

**Comment by dobromir-hristov** [comment]
The validator wrapper should allow for any generic validator, not just the ones we have shipped. Try not to extend it's type from that list of items, as it becomes a maintenance nightmare.

File: packages/validators/index.d.ts [hunk 1]
```diff
@@ -83,18 +83,29 @@ export interface MessageProps {
   $propertyPath: string,
 }
 
-export type ValidatorWrapper = (...args: unknown[]) => ValidationRuleWithParams
+export type ValidatorWrapper =
```
Comment (derdem) [inline packages/validators/index.d.ts:86]: I tried to look for a more generic solution, but in the end this was the best I could come up with

**Comment by derdem** [comment]
> The validator wrapper should allow for any generic validator, not just the ones we have shipped. Try not to extend it's type from that list of items, as it becomes a maintenance nightmare.

I tried out various things to get it work, however I didn't succeed without making use of the `any` type. I think that the current changes allow to make use of the `createI18nMessage` function in a quite general way. In all cases, which I tested the return value from the `withI18nMessage` function has the same structure as the input. 

At the same time, arguments to `withI18nMessage` which do not follow the appropiate structure are marked as faulty. 

I am curious to hear your feedback. 

Below are my testcases. 

```typescript 
import { ValidatorResponse } from "@vuelidate/core";
import {
    alpha,
    alphaNum,
    numeric,
    between,
    email,
    ipAddress,
    macAddress,
    maxLength,
    minLength,
    required,
    requiredIf,
    requiredUnless,
    sameAs,
    url,
    or,
    and,
    not,
    minValue,
    maxValue,
    integer,
    decimal
  } from "./index";
import {createI18nMessage} from "./index";

const customValidator1 = (text: string) => true
const customValidator2 = (text: string) => ({$valid: true})
const customValidator3 = (text: string): Promise<boolean> => new Promise((resolve) => {resolve(true)})
const customValidator4 = (text: string): Promise<ValidatorResponse> => new Promise((resolve) => {resolve({$valid: true})})

const notValidator1 = (arg: any) => ""
const notValidator2 = (arg: any) => 0
const notValidator3 = (arg: any) => ({})
const notValidator4 = (arg: any) => ([])


const t = (path: string, params: { [key: string]: any; model: string; property: string; }) => path
const withI18nMessage = (createI18nMessage({t}));

const min8 = minValue(8);

// ValidationRuleWithoutParams
const alphaI18N = withI18nMessage(alpha);
const alphaNumI18N = withI18nMessage(alphaNum);
const numericI18N = withI18nMessage(numeric);
const emailI18N = withI18nMessage(email);
const ipAddressI18N = withI18nMessage(ipAddress);
const requiredI18N = withI18nMessage(required);
const urlI18N = withI18nMessage(url);
const integerI18N = withI18nMessage(integer);
const decimalI18 = withI18nMessage(decimal);

// ValidationRuleWithParams
const min8I18N = withI18nMessage(min8)

// ValidatorFnc
const customValidator1I18n = withI18nMessage(customValidator1);
const customValidator2I18n = withI18nMessage(customValidator2);
const customValidator3I18n = withI18nMessage(customValidator3);
const customValidator4I18n = withI18nMessage(customValidator4);

// ValidationWrapper
const betweenI18N = withI18nMessage(between);
const macAddressI18N = withI18nMessage(macAddress);
const maxLengthI18N = withI18nMessage(maxLength);
const minLengthI18N = withI18nMessage(minLength);
const requiredIfI18N = withI18nMessage(requiredIf);
const requiredUnlessI18N = withI18nMessage(requiredUnless);
const sameAsI18N = withI18nMessage(sameAs);
const orI18N = withI18nMessage(or);
const andI18N = withI18nMessage(and);
const notI18N = withI18nMessage(not);
const minValueI18N = withI18nMessage(minValue);
const maxValueI18N = withI18nMessage(maxValue);

// Not ValidatonFnc
const notValidator1I18N = withI18nMessage(notValidator1) // Typescript throws an error
const notValidator2I18N = withI18nMessage(notValidator2) // Typescript throws an error
const notValidator3I18N = withI18nMessage(notValidator3) // Typescript throws an error
const notValidator4I18N = withI18nMessage(notValidator4) // Typescript throws an error


```

**Comment by dobromir-hristov** [comment]
This is awesome!
